//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mark1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Araçlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Araçlar()
        {
            this.TB_Müsteriler = new HashSet<TB_Müsteriler>();
            this.TB_Personel = new HashSet<TB_Personel>();
            this.TB_şoförler = new HashSet<TB_şoförler>();
        }
    
        public int AraçID { get; set; }
        public int PlakaID { get; set; }
        public string Marka { get; set; }
        public Nullable<int> KoltukID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Müsteriler> TB_Müsteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Personel> TB_Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_şoförler> TB_şoförler { get; set; }
    }
}
