//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mark1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Personel
    {
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public Nullable<int> AraçID { get; set; }
    
        public virtual TB_Araçlar TB_Araçlar { get; set; }
    }
}
