//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mark1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_şoförler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_şoförler()
        {
            this.TB_Seferler = new HashSet<TB_Seferler>();
        }
    
        public int SöförID { get; set; }
        public string Söförad { get; set; }
        public string Söförsoyad { get; set; }
        public Nullable<int> AraçID { get; set; }
        public Nullable<double> TotalTutar { get; set; }
    
        public virtual TB_Araçlar TB_Araçlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Seferler> TB_Seferler { get; set; }
    }
}
